<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Trường nhập Mật khẩu (MatKhau) trên trang đăng nhập</description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>a1b2c3d4-e5f6-7890-abcd-ef1234567802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MatKhau']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input#MatKhau</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MatKhau</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
</WebElementEntity>
