<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Input Email trên trang đăng nhập – asp-for="Email" → id="Email"</description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>1a000001-0000-0000-0000-000000000001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
</WebElementEntity>
