<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Input mật khẩu trên trang đăng nhập – explicit id="pwInput" (KHÔNG phải MatKhau)</description>
   <name>input_MatKhau</name>
   <tag></tag>
   <elementGuidId>1a000001-0000-0000-0000-000000000002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#pwInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
</WebElementEntity>
