analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3458635,"name"\:"Sample - HR Web App \#3458635","teamId"\:3439195,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3485309,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3439195,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
