// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHoc5.Web.Data;

#nullable disable

namespace QuanLyKhoaHoc5.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524133101_AddKyHocAndDiemKyHocId")]
    partial class AddKyHocAndDiemKyHocId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("HocVienId", "LopHocId")
                        .IsUnique();

                    b.ToTable("DangKyKhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DangKyId")
                        .HasColumnType("int");

                    b.Property<double?>("DiemCuoiKy")
                        .HasColumnType("float");

                    b.Property<double?>("DiemGiuaKy")
                        .HasColumnType("float");

                    b.Property<double?>("DiemTongKet")
                        .HasColumnType("float");

                    b.Property<bool>("IsKhoa")
                        .HasColumnType("bit");

                    b.Property<int?>("KyHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetGiangVien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("XepLoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyId")
                        .IsUnique();

                    b.HasIndex("KyHocId");

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BangCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KinhNghiem")
                        .HasColumnType("int");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MaGiangVien")
                        .IsUnique();

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.GoiYKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<double?>("DiemPhuHop")
                        .HasColumnType("float");

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocGoiYId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoGoiY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGoiY")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanHoiAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptGuiDi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KhoaHocGoiYId");

                    b.ToTable("GoiYKhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.HocVien", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHocVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("NgonNguQuanTam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrinhDoHienTai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaHocVien")
                        .IsUnique();

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhBia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgonNgu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoiDungChuongTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoBuoiMoiTuan")
                        .HasColumnType("int");

                    b.Property<int>("SoChoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiGianMoiBuoi")
                        .HasColumnType("int");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.KyHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("KyHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.LichHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("LichHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKhaiGiang")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HocVien");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.PhanCongGiangDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("PhanCongGiangDays");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.ThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhBill")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDuyetId");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanLienKet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiNhanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.ChatHistory", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.DangKyKhoaHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.HocVien", "HocVien")
                        .WithMany("DangKys")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.LopHoc", "LopHoc")
                        .WithMany("DangKys")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.Diem", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.DangKyKhoaHoc", "DangKy")
                        .WithOne("Diem")
                        .HasForeignKey("QuanLyKhoaHoc5.Web.Models.Entities.Diem", "DangKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.KyHoc", "KyHoc")
                        .WithMany("Diems")
                        .HasForeignKey("KyHocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DangKy");

                    b.Navigation("KyHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.GiangVien", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", "NguoiDung")
                        .WithOne("GiangVien")
                        .HasForeignKey("QuanLyKhoaHoc5.Web.Models.Entities.GiangVien", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.GoiYKhoaHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.HocVien", "HocVien")
                        .WithMany("GoiYs")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.KhoaHoc", "KhoaHocGoiY")
                        .WithMany("GoiYs")
                        .HasForeignKey("KhoaHocGoiYId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHocGoiY");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.HocVien", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", "NguoiDung")
                        .WithOne("HocVien")
                        .HasForeignKey("QuanLyKhoaHoc5.Web.Models.Entities.HocVien", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.LichHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.LopHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.GiangVien", "GiangVien")
                        .WithMany("LopHocs")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.PhanCongGiangDay", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.GiangVien", "GiangVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.ThanhToan", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.ThongBao", b =>
                {
                    b.HasOne("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", "NguoiNhan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.DangKyKhoaHoc", b =>
                {
                    b.Navigation("Diem");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.GiangVien", b =>
                {
                    b.Navigation("LopHocs");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.HocVien", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("GoiYs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.KhoaHoc", b =>
                {
                    b.Navigation("GoiYs");

                    b.Navigation("LichHocs");

                    b.Navigation("LopHocs");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.KyHoc", b =>
                {
                    b.Navigation("Diems");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.LopHoc", b =>
                {
                    b.Navigation("DangKys");
                });

            modelBuilder.Entity("QuanLyKhoaHoc5.Web.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("HocVien");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
